### ISSUE TITLE
Issue moderation statements for GPT3Discord to execute

### ISSUE THREAD

**Issue by noalear** [Kav-K/GPT3Discord#101]
In addition to alerts, bot moderation could consist of executing moderation commands such as moving users to other channels, muting people in voice channels, assigning roles, etc. These commands would need to be made by users within particular roles. If possible, it could apply to multiple users in a single statement. 

This would be most useful in the context of voice transcription. In this case, the action should be done after the voice reply is completed. The subjects of 'me' and 'myself' should reference the user making command.

Examples:
Admin: "GPT, move users X, Y, and Z to the Ready Room."
GPT: "Roger, moving users X, Y, and Z to the Ready Room, Admin."
Then GPT moves users

Admin: "GPT, assign the role of Bot Developer to users X, Y, and Z."
GPT: "Confirmed. Assigning the role of Bot Developer to X, Y, and Z, Admin."
Then GPT assigns users

**Comment by Kav-K** [comment]
While I like this idea a lot, it's too difficult to implement as we would need a separate NLP service that is more reliable and consistent than GPT3 to reliably extract users accurately and extract the actions to do, it also would require a whole new processing framework to translate these statements into actions, I'm going to close this for now as I don't see myself working on this in the foreseeable future
