### ISSUE TITLE
Add a health endpoint to the container

### ISSUE THREAD

**Issue by falkoro** [Kav-K/GPT3Discord#106]
For testing, debugging and hosting purposes it would be nice of the application had a health endpoint. A possible solution is to import a library like healthcheck: 

```
from healthcheck import HealthCheck

health = HealthCheck()

@health.route("/health")
def healthcheck():
    return health.run()
```

It's also possible to use Flask or configure the healthcheck in the container:

```
HEALTHCHECK --interval=30s --timeout=3s \
  CMD curl --fail http://localhost:5000/health || exit 1
```

**Comment by Kav-K** [comment]
@falkoro What should the endpoint return? Does it not matter?

**Comment by Kav-K** [comment]
Done!
