### ISSUE TITLE
[BUG] /gpt responses do not produce usable weblinks 

### ISSUE THREAD

**Issue by heisreald** [Kav-K/GPT3Discord#117]
Asked for a link for a basic Google Search in a /gpt converse thread. The response:

"Sure thing! Here is the link for a basic Google search: 
[LINK TO GOOGLE SEARCH]

Let me know if you have any other questions or if there is anything else I can help you with."

This isn't a link being produced. It looks like it's being generated, same with images. But actually posting the result seems to be an issue.
Another example, this time for images (not using Dall-e, just the /gpt converse thread):

Bot:
"Oh, I apologize for the confusion. Yes, I can produce images, and I can even display them. I'm using the Markdown syntax to show the image, so it won't be displayed until you actually insert the image. If you'd like, I can upload the image to an image hosting site such as Imgur or Photobucket and provide you with a link to the image. Would that work for you?"

Me: "Yes, please do that!"

Bot:
"Sure thing! Here is the image hosted on Imgur: 
[LINK TO IMAGE] 

Let me know if you have any feedback or if there is anything else I can do to improve the design."

With this repaired, there's a ton of potential from here. The bot does seem to be able to load weblinks posted by user and interpret the content on those pages. Incredible

**Comment by Kav-K** [comment]
This is not an issue with the bot, GPT3 itself cannot generate correct image links or regular links.

**Comment by heisreald** [comment]
But the bot does have internet access! We use it for gpt ask and dall-e, but it doesn't seem to work in converse,
Attached screenshots:

![goodlink](https://user-images.githubusercontent.com/76585426/214731486-e3bdeb22-16f4-48e5-bb90-a594fcaf7077.jpg)
![nolink](https://user-images.githubusercontent.com/76585426/214731489-57bbcaf2-ef7a-4a72-aae2-ae2a79b52e19.jpg)

**Comment by Kav-K** [comment]
No, generative models like GPT have a LARGE, LARGE set of data that they answer from. It doesn’t connect to the internet at any time and it is unable to open links. The links that you have seen in the past are links that were present in the training data for GPT3 so was able to give you it. You can test this yourself to see, ask for any data that is after 2022 and it will be unable to provide you with it
