### ISSUE TITLE
Unable to send requests in a converse thread.

### ISSUE THREAD

**Issue by jfaithedu** [Kav-K/GPT3Discord#132]
# Issue
I'm having an issue with GPT converse command - it is not responding to subsequent requests after the initial response is received. Instead, it returns an error "You are already waiting for a response, please wait and speak afterwards." to the user.

Steps to reproduce:
1. Invoke GPT converse command with an initial prompt (opener)
2. Send subsequent requests to GPT converse command

Expected result: 
GPT converse command should respond to subsequent requests.

Actual result:
GPT converse command returns an error "You are already waiting for a response, please wait and speak afterwards." to the user.

Environment:
- OS: Linux
- Version of GPT Converse command: most recent

Additional information: Issue report written by GPT-3

**Comment by jfaithedu** [comment]
I should note that a server reboot and fresh package install did not solve the issue.

**Comment by Kav-K** [comment]
This is not reproducible, it may be an issue with the API not having responded properly.

It seems to work for me:
![image](https://user-images.githubusercontent.com/21161101/216515666-49a0c0c2-bf00-4349-a4ca-60c145a2ac75.png)

**Comment by jfaithedu** [comment]
Thanks for checking this out. Luckily, I was able to reproduce the issue:

The issue seems to arise when receiving responses in a converse thread which are wrapped as below:

**Problematic wrapping:**

`
 ''' ``` CONTENT ``` '''
`

**in a response:**

`
{'id': 'OMITTED', 'object': 'text_completion', 'created': 1675457157, 'model': 'text-davinci-003', 'choices': [{'text': "\n\n'''\n```OMITTED\n```\n'''<|endofstatement|>", 'index': 0, 'logprobs': None, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 1803, 'completion_tokens': 813, 'total_tokens': 2616}}
`

**Such a response creates an error on the client:**
` 'NoneType' object has no attribute 'id'`

**Which leads to**
`AttributeError: 'Message' object has no attribute 'send_followup'`

This leaves the thread response appear as unresolved in discord, with no buttons to retry or end the conversation.
(note, the debugging channel does not display the problematic response)


Next, when attempting to generate a new response by replying, you are met with the error that you are still awaiting the initial response. (with no feedback in the bot console)
`
You are already waiting for a response, please wait and speak afterwards.
`

**Finally, if you attempt to end the thread by clicking "End Conversation" on a previous response, you are again met with the issue  upon sending your first response in the new thread.**
`
You are already waiting for a response, please wait and speak afterwards.
`

## Logs:

### on receiving problematic response
`
The current usage is 1.56302 credits
Response -> {'id': 'OMITTED', 'object': 'text_completion', 'created': 1675457157, 'model': 'text-davinci-003', 'choices': [{'text': "\n\n'''\n```RESPONSE-OMITTED\n```\n'''<|endofstatement|>", 'index': 0, 'logprobs': None, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 1803, 'completion_tokens': 813, 'total_tokens': 2616}}

Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/services/text_service.py", line 437, in encapsulated_send
    response_message.id
AttributeError: 'NoneType' object has no attribute 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/discord/client.py", line 377, in _run_event
    await coro(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/cogs/text_service_cog.py", line 553, in on_message
    if await TextService.process_conversation_message(
  File "/usr/local/lib/python3.9/dist-packages/services/text_service.py", line 641, in process_conversation_message
    await TextService.encapsulated_send(
  File "/usr/local/lib/python3.9/dist-packages/services/text_service.py", line 503, in encapsulated_send
    await ctx.send_followup(embed=embed)
AttributeError: 'Message' object has no attribute 'send_followup'
`

## Solution

At first I could not get around the issue, however today the issue is easily resolved by killing and restarting the bot process.
