### ISSUE TITLE
Multiple conversations in parallel without closing old ones

### ISSUE THREAD

**Issue by jnpatrick99** [Kav-K/GPT3Discord#145]
**Is your feature request related to a problem? Please describe.**
Can we have multiple conversations/threads that are not closed and can be continued any time? 

**Describe the solution you'd like**
Do not force user to use "End conversation" button on old conversations every time you need to start a new one.
Also do not rename conversations to "Closed-GPT" - so it would be easier to navigate old convos. 
Maybe name them by first opener line?
Also allow to continue any conversation any time.

**Additional context**
The original ChatGPT has all its conversations "open" for various topics. You don't need to click "end conversation" every time you start a new one. It's easy to continue any previous conversation there is.

**Comment by Kav-K** [comment]
Done! 10.5.0

**Comment by jnpatrick99** [comment]
Wow!
