### ISSUE TITLE
ValueError: ALLOWED_GUILDS is not defined properly in the environment file!Please copy your server's guild ID and put it into ALLOWED_GUILDS in the .env file.For example a line should look like: `ALLOWED_GUILDS="971268468148166697"`

### ISSUE THREAD

**Issue by Ndh474** [Kav-K/GPT3Discord#148]
when i run python3.9 gpt3discord.py, it happened

**Comment by Kav-K** [comment]
Hi, there are no issues with ALLOWED_GUILDS on the current main branch, please check the following
- The file has to be named EXACTLY `.env`
- The server IDs that you put into ALLOWED_GUILDS must have the bot joined in them
- The line should look like `ALLOWED_GUILDS="706657592578932797,706657592578932792,..etc"` if there are multiple allowed guilds or `ALLOWED_GUILDS="706657592578932797"` if just one.
