### ISSUE TITLE
Option to cache /search embeddings in an index file

### ISSUE THREAD

**Issue by Raecaug** [Kav-K/GPT3Discord#156]
When searching Google using /search, sometimes responses require large numbers of embeddings to answer, for instance citing a page of documentation or a manual. Pages like this must be indexed manually using /index add to ask followup questions, which can be expensive.

In order to minimize token usage, and to aid in asking followup queries, it would be nice to have the option to cache embeddings from pages searched into a(n) index file(s).

This should prevent repeat embedding costs, especially on heavier webpages and documents.

**Comment by Kav-K** [comment]
Done! Indexes created by search are cached for use with /index. there's a new param for /index named `search_index`
