### ISSUE TITLE
Multi-user conversations in a thread

### ISSUE THREAD

**Issue by Kav-K** [Kav-K/GPT3Discord#16]
Allow for the conversation system to send multiple users to GPT3 in the conversation history.

For example, we should key the user based on their discord name and the conversations should look like this:

{CONVERSATION CONTEXT PRE-TEXT}
Kaveen: Hey!
GPTie: Hello there Kaveen, how can I help?
Bob: Hey GPTie!
GPTie: Hey to you as well Bob!

For the initial version of this, each message sent by any user should cause an API Request to happen. In later, and more sophisticated versions of this, I want the API request to happen 10 seconds after no conversation activity has happened, so that we don't have to make an individual request for each user's message, especially if the users are talking to each other and not GPTie.

**Comment by Kav-K** [comment]
This has been deprioritized, I will do async for requests and image concat before this gets any thought :)

**Comment by Kav-K** [comment]
I take back what I said about this being very easy earlier, this is super tough with the current architecture, everything is keyed to 1 user, and not keyed on threads... will continue looking into it

**Comment by sudoskys** [comment]
Multiple users in one session context?

**Comment by Kav-K** [comment]
Can you elaborate a bit more on what you mean by mixed message buckets? :)

**Comment by sudoskys** [comment]
> Can you elaborate a bit more on what you mean by mixed message buckets? :)

Each user has a message bucket
{ask reply time} 
This is used to remember
Then each group also has a bucket of messages.
This allows you to combine them, filter them, match and mix content.
