### ISSUE TITLE
Setup for selecting the GPT3Discord tag

### ISSUE THREAD

**Issue by SAN4EZDREAMS** [Kav-K/GPT3Discord#179]
It would be very nice if you could configure in more detail how and where exactly the bot will respond to its @GPT3Discord tag. This way there will be no chaos on the server, because then the bot will only respond to specialized channels created specifically for communicating with it.

**Comment by Kav-K** [comment]
This is done and will be out in version 10.7.5+, currently though no option to select which channels the bot will do taggable responses, this part is deprioritized and will be done in the future, for now it's globally toggle-able, can you make a new issue for the feature request of channel selection for where the bot will respond?
