### ISSUE TITLE
[BUG] When I try to run the script, I get this error:

### ISSUE THREAD

**Issue by IncognitoTGT** [Kav-K/GPT3Discord#207]
This is in a Docker container (not yours).

```
Traceback (most recent call last):
  File "gpt3discord.py", line 14, in <module>
    from cogs.search_service_cog import SearchService
  File "/cogs/search_service_cog.py", line 10, in <module>
    from models.search_model import Search
  File "/models/search_model.py", line 39, in <module>
    class Search:
  File "/models/search_model.py", line 147, in Search
    def index_webpage(self, url) -> list[Document]:
TypeError: 'type' object is not subscriptable
```

**Comment by Kav-K** [comment]
Hey @IncognitoTGT What OS are you on, what python version, and what version of llama-index is on your system?

**Comment by IncognitoTGT** [comment]
Hi. I'm using the default Docker image for python, (I think 3.9), and not sure what llama-index is.

**Comment by Kav-K** [comment]
@Hikari-Haru any ideas what this might be for docker?

**Comment by Hikari-Haru** [comment]
Haven't seen this while running any of our images, so not sure really.

**Comment by IncognitoTGT** [comment]
OK, I might try one of yours. 
Please don't close it yet.

**Comment by Kav-K** [comment]
Closing. No further information was provided in a week
