### ISSUE TITLE
[BUG]  dalle optimize not working with GPT-4

### ISSUE THREAD

**Issue by evilalmus** [Kav-K/GPT3Discord#236]
**Describe the bug**
dalle optimize not working with GPT-4

**To Reproduce**
Enable GPT-4 and try to use `/dalle optimize`

**Expected behavior**
command works and optimizes prompt

**actual behavior**
The API returned an invalid response: The API returned an invalid response: This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions

**Comment by Kav-K** [comment]
fixed
