### ISSUE TITLE
[BUG] Bot unable to parse emoji's

### ISSUE THREAD

**Issue by Raecaug** [Kav-K/GPT3Discord#239]
Bot doesn't seem to properly parse emoji's.
![image](https://user-images.githubusercontent.com/23362597/226456543-148e4646-a4eb-4769-98a9-ebf4e6ec9a0b.png)

May be related to #206?
![image](https://user-images.githubusercontent.com/23362597/226456404-c62a9f52-2ba8-48ab-b2dd-96ab054cd205.png)

**Comment by Kav-K** [comment]
Is directly linked to #206, will do that
