### ISSUE TITLE
Add Docker Support + Image Uploading

### ISSUE THREAD

**Issue by cooperlees** [Kav-K/GPT3Discord#24]
**Is your feature request related to a problem? Please describe.**
Docker offers a cleaner env dedicated to the code. Will allow me to run it on my VPS in a clean way as I don't want all the deps and to install python 3.9 on it directly. Would rather it in a container.

**Describe the solution you'd like**
Add a Docker file to the repo and then make some CI to build and upload docker images on every merge to main.

**Describe alternatives you've considered**
- I have https://github.com/Kav-K/GPT3Discord/pull/22 up to add a Dockerfile + concept of saving file into a persistent data directory
- Once this is merged I'll put up a PR to make GitHub actions push to docker hub on every merge to main

**Additional context**
I'm willing to do all the PRs. Will just need you to create a docker hub account and add a docker API token into Github secrets to enable uploading docker images from GitHub actions CI.

**Comment by Kav-K** [comment]
Merged! I will create a dockerhub account and add the API secret first thing tomorrow.

**Comment by cooperlees** [comment]
Awesome, thanks. This will make it much easier for me to automate upgrading and installing via ansible.

The docker hub action needs token username and secret. The names are:
- DOCKERHUB_USERNAME
- DOCKERHUB_TOKEN

I will be copying and simplifying the GitHub action from from here: https://github.com/pypa/bandersnatch/blob/main/.github/workflows/docker_upload.yml

**Comment by Kav-K** [comment]
Sounds good, I’ll update here when those are added soon

**Comment by Kav-K** [comment]
I've just added these tokens

**Comment by Kav-K** [comment]
Do I need to create a repository on dockerhub initially for this?

**Comment by cooperlees** [comment]
Yes. I had forgot, it seems you need to go to your respective docker hub dashboard and create - Here is the link of mine: https://hub.docker.com/repository/create?namespace=cooperlees

TIL about the capitals:
```
Error: buildx failed with: ERROR: invalid tag "Kav-K/GPT3Discord:latest": repository name must be lowercase
```
So definitely needs to be your username + name in lowercase: e.g. `username/gpt3discord`

I believe creating and fixing the case we should then be fine.

**Comment by Kav-K** [comment]
Got it, where `username` is the dockerhub username? So, in my case if my username is kaveenk, `kaveenk/gpt3discord`?

**Comment by Kav-K** [comment]
Looks like it's all good now!

**Comment by Kav-K** [comment]
Can you give me a bit more information on how latest and how latest_non_release works?

Am I correct in saying that `latest` contains the most recent github release available on this repo? Which, in this case, is V1.6? And then am I also correct in saying that latest_non_release will be any commit that I push to main?

**Comment by cooperlees** [comment]
Yes, your interpretation is correct.

latest_release is if we go and make an official release via https://github.com/Kav-K/GPT3Discord/releases
- 1.6 was done before we landed this CI, so there is nothing tagged 1.6 at the moment @ https://hub.docker.com/r/kaveenk/gpt3discord/tags
  - But we have latest and latest non release.

`latest_release` will only get pushed next time you do a GitHub release and the tag you apply to the GitHub repo will be used as the "version" tag.

**Comment by Kav-K** [comment]
Got it! Makes perfect sense, I've just done a new release for the docker support, thank you very much again for all the contributions and help here, it's very much appreciated!!

**Comment by cooperlees** [comment]
No worries. I appreciate all the work you've done making the bot work.

I know python well, but not the gpt3 + discord APIs :) So you saved me a lot of time. Happy to help with packaging etc.

Will do the PyPI upload PR soon - It too will need tokens :) Will comment on the PR

**Comment by Kav-K** [comment]
My pleasure, and sounds good re: PyPI, tokens, and etc! Thanks again in advance!!

Please also let me know if there are any feature suggestions or changes for the GPT3/Discord side that you'd like me to implement, as I'd be happy to.

**Comment by cooperlees** [comment]
https://hub.docker.com/r/kaveenk/gpt3discord/tags now has latest_release and 1.7 :)

<img width="562" alt="Screenshot 2022-12-30 at 4 53 40 PM" src="https://user-images.githubusercontent.com/3005596/210120209-e975a31c-0a06-4820-968e-fee5137ea8d8.png">

**Comment by Kav-K** [comment]
Looks great, will be doing that now!
