### ISSUE TITLE
[BUG] 3 word limit for dalle draw should be removed 

### ISSUE THREAD

**Issue by CDG-c0de** [Kav-K/GPT3Discord#240]
**Dalle draw command prompts for minimum of 3 words**
In its current state the program prompts for a minimum of 3 words when trying to use the dalle draw command, however dalle does not enforce a minimum of 3 words for the prompts. The minimum can be set to 1 word.

**To Reproduce**
1. On discord server with bot run `/dalle draw Arnold Schwarzenegger`
2. Bot will reply with error requesting a prompt between 3 and 75 words long
3. Edit line 1140 in file `models/openai_model.py` to: `if words < 1 or words > 75:`
4. Maybe restart bot server
5. Now again run `/dalle draw Arnold Schwarzenegger` on discord server with bot
6. Watch as the bot produces and successfully returns images of Arnold Schwarzenegger

**Expected behavior**
Expected behavior would be: the bot accepting prompts that are 1 word long, or longer.

**Screenshots**
![image](https://user-images.githubusercontent.com/82316777/226502619-3dc0fb53-189f-4a8a-963d-fde37fc6b538.png)

**Comment by Kav-K** [comment]
Removed the 3 word minimum
