### ISSUE TITLE
[BUG] /gpt converse times out responding

### ISSUE THREAD

**Issue by Raecaug** [Kav-K/GPT3Discord#243]
When threads get lengthy, /gpt converse will begin timing out responses to the user. Replies can take upwards of multiple minutes, and result in timeout errors in the logs.

**Comment by Raecaug** [comment]
Conversations running 30-50 messages long begin to display this. Sometimes earlier, it's a bit unpredictable.
![image](https://user-images.githubusercontent.com/23362597/227431095-5b646e51-8a12-4910-a216-db20858764a5.png)

**Comment by Hikari-Haru** [comment]
It's a bug unrelated to conversation length at all, it crops up even if there are zero conversations

**Comment by Kav-K** [comment]
Is the conversation entirely unusable and dead when this starts popping up?

**Comment by Raecaug** [comment]
At that point yes, it becomes unresponsive to commands and further messages. I've attempted to replicate this recently but have had no success. I think this cropped up more frequently with the rampant API outages last week.

**Comment by Raecaug** [comment]
@Kav-K Managed to catch it occurring again:

![image](https://user-images.githubusercontent.com/23362597/228425537-9da65806-72d1-449a-b303-e7011532853c.png)

![image](https://user-images.githubusercontent.com/23362597/228425682-86c8c903-c9d4-4386-8dee-3b4a7f739cd2.png)

**Comment by Kav-K** [comment]
TODO: Catch timeout error gracefully, include it in the retry backoff conditions

**Comment by Kav-K** [comment]
Fixed! More graceful error message as well
