### ISSUE TITLE
Different API Key for DALL-E and GPT

### ISSUE THREAD

**Issue by bt** [Kav-K/GPT3Discord#246]
**Is your feature request related to a problem? Please describe.**
I have a use-case in which I've been asked to separate my image generation usage from my GPT usage.

**Describe the solution you'd like**
To do so, I have two separate accounts mapped to different payment methods.

**Describe alternatives you've considered**
I've therefore changed the code so that I can input a separate DALLE_KEY for use with DALL-E. If this environment variable is not defined, it will default back to the OpenAI one.

**Additional context**
Is this something that may be valuable for the project? I can open a PR if so.

**Comment by Raecaug** [comment]
I could see a use for this, especially if it can be optionally enabled.

**Comment by bt** [comment]
> I could see a use for this, especially if it can be optionally enabled. 

Yep, so in my fork, DALLE_KEY is only used if it's defined. Otherwise it is completely transparent to the user and defaults back to the OPENAI_KEY.

**Comment by Kav-K** [comment]
@bt Could you PR? :)

**Comment by Kav-K** [comment]
I won't be doing this feature myself, but would love to review a PR if you add one for this later
