### ISSUE TITLE
Install via python module

### ISSUE THREAD

**Issue by cooperlees** [Kav-K/GPT3Discord#25]
**Is your feature request related to a problem? Please describe.**
Create a `setup.py` or `pyproject.toml` and install using `pip`.

**Describe the solution you'd like**
Today we have to manually install dependencies and copy the python source files into the python environment. Lets use a defined module install method to do this for us and build sdists + wheels.

**Describe alternatives you've considered**
We can use traditional setup.py or more modern pyproject.toml. Happy to do either.

**Additional context**
https://packaging.python.org/en/latest/tutorials/packaging-projects/

**Comment by Kav-K** [comment]
Hey Cooper, I'd love to use pyproject.toml, but I've never really done anything with it before, and have little to no experience. I've been using requirements.txt my whole life ;)

**Comment by cooperlees** [comment]
Ok - Once we merge my other PR I can put up the PR for adding `pyproject.toml` building/installing support.

Branch Commit: https://github.com/cooperlees/GPT3Discord/commit/36e5c3d548375a223e768a079734135a9f149e24
New building CI passing: https://github.com/cooperlees/GPT3Discord/actions/runs/3805288220/jobs/6473120751

**Comment by Kav-K** [comment]
@cooperlees

So I've merged the docker and pyproject PRs, and I'm a bit confused about some of the errors I'm seeing on actions:
![image](https://user-images.githubusercontent.com/21161101/210116832-c99b4832-d594-4f0f-afb6-c1f13432f21d.png)

My original deploy action also fails with:
![image](https://user-images.githubusercontent.com/21161101/210116843-a52c0eb3-ef5d-4587-ab89-ae47286e6349.png)

Is this because there needs to be some sort of initial setup to get this started and going with Docker? I'm sorry, not very well versed with this.

**Comment by Kav-K** [comment]
I've made a repo on dockerhub called `gpt3discord`, and updated the docker action file to use the lowercase name, not sure if this is correct, trying it out

**Comment by Kav-K** [comment]
![image](https://user-images.githubusercontent.com/21161101/210118168-1d7e1e8b-5e53-4a6e-8305-e1b141929c2e.png)
No luck, will revert my changes to the docker action.

**Comment by cooperlees** [comment]
As I commented on the PR - lets try create and rerun the action: https://hub.docker.com/repository/create?namespace=cooperlees <-- Replace cooperlees with your username :)

**Comment by cooperlees** [comment]
Do you have interest uploading to [PyPI](https://pypi.org/)? If so, I will do a PR for that later today/yomottoe too.

**Comment by Kav-K** [comment]
Sounds good, applying the changes now. 

Regarding PyPI, can you give me some more information on what this would enable users to do? As far as I understand, PyPI is for packages and libraries, but my project doesn't seem like a good fit for it? I guess I'm just unfamiliar

**Comment by Kav-K** [comment]
Also, I was curious why my old deploy pipeline failed after these changes, that file wasn't touched? It seems like it's doing something with docker, but not sure what prompted it to?

**Comment by cooperlees** [comment]
> Sounds good, applying the changes now.
> 
> Regarding PyPI, can you give me some more information on what this would enable users to do? As far as I understand, PyPI is for packages and libraries, but my project doesn't seem like a good fit for it? I guess I'm just unfamiliar

Uploading to PyPI (now we're a valid python module) just allows someone to `pip install gpt3discord` and install that way. Just like how you use black for example. :)

> Also, I was curious why my old deploy pipeline failed after these changes, that file wasn't touched? It seems like it's doing something with docker, but not sure what prompted it to?

I did `git mv main.py gpt3discord.py` ... And that step is trying to copy `main.py` that no longer exists ...

**Comment by Kav-K** [comment]
> > Sounds good, applying the changes now.
> > Regarding PyPI, can you give me some more information on what this would enable users to do? As far as I understand, PyPI is for packages and libraries, but my project doesn't seem like a good fit for it? I guess I'm just unfamiliar
> 
> Uploading to PyPI (now we're a valid python module) just allows someone to `pip install gpt3discord` and install that way. Just like how you use black for example. :)
> 
> > Also, I was curious why my old deploy pipeline failed after these changes, that file wasn't touched? It seems like it's doing something with docker, but not sure what prompted it to?
> 
> I did `git mv main.py gpt3discord.py` ... And that step is trying to copy `main.py` that no longer exists ...

Oops I didn't catch that, I thought it was somehow trying to pull from the docker repo to deploy based on the messages, apologies!

Being able to just pip install gpt3discord sounds absolutely amazing, and I'd love to do that! However, how does this work for the .env file? How do users configure things like the image prompt optimizer pretext, and etc? After pip installing gpt3discord, what does this project it look like on the system?

**Comment by cooperlees** [comment]
`pip install gpt3discord` would install the script to /usr/local/bin or depends on your python setup. 

Someone would have to copy to `.env` file to the location where the binary gets installed for now, but we can possibly improve that in the future. Generally I default config files to /etc/something.conf - here `/etc/gpt3discord.conf` and have a CLI argument to change the location if someone wanted to put it somewhere else. I've never used the env file you have. Don't know if the API takes a custom file path, if so we could make a new `--config / -c` CLI argument maybe?

But lots of options there.

**Comment by Kav-K** [comment]
Got it, that makes sense, and I think that's a good initial approach to put the env contents in `/etc/gpt3discord.conf` along with a cli argument to specify the config path. However, what about other configurable files? The image prompt optimizer and the conversation starter pretext are both in separate files, I guess I should just move those into the .env/config?

**Comment by Kav-K** [comment]
I'm seeing this error when PyPI is uploading:
![image](https://user-images.githubusercontent.com/21161101/210134674-46ece79c-a4a9-46d7-9278-4865902aff79.png)

I bumped the version number to 2.0.1 but it doesn't seem to be picking it up, is there anything else that I have to do // other locations I should change before creating a release?

**Comment by Kav-K** [comment]
I think I actually just messed up the github release, I did another one today and it seems to work all good :)
