### ISSUE TITLE
[BUG] discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

### ISSUE THREAD

**Issue by KZkici** [Kav-K/GPT3Discord#250]
May I know how it was fixed, as I think everything is setup accordingly, yet still get the same error:
I've tried everything, even new bots, new permissions (always admin) etc.. nothing works, but if i use same bot for https://github.com/Zero6992/chatGPT-discord-bot it works
I've tried other ChatGPTs and it works as well as other Discord bots, not sure what else I can do to get this one to work.

Help me find a solution for this please

Note: Ubuntu Server 22.04 LTS 
I've searched previous issues and discussions I found some vague discussions but no real solutions about this issue.

**Comment by miki-tnt** [comment]
Same here, anyone have an idea?

**Comment by Kav-K** [comment]
This is not an issue with the bot, please give your bot admin permissions and then enable *all of the intents in the discord developer portal*. Please make sure you add the bot with the "bot" scope and the "application.commands" scope when you are making an OAUTH link to invite the both to your server

**Comment by KZkici** [comment]
well for scopes: bot, application commands is on and administrator, with all 3 intents on.
