### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SnowbambooXsshallot** [Kav-K/GPT3Discord#256]
**Describe the bug**
ValueError: ALLOWED_GUILDS is not defined properly in the environment file!Please copy your server's guild ID and put it into ALLOWED_GUILDS in the .env file.For example a line should look like: `ALLOWED_GUILDS="971268468148166697"`

I have a 19 digit ID

**Comment by Kav-K** [comment]
Did you put it in the environment file? You need to make a file named `.env` and put the line `ALLOWD_GUILDS="your guild ID here"` in it.
