### ISSUE TITLE
[BUG]  Slash Command `/index recurse-link` always fails with cryptic error:

### ISSUE THREAD

**Issue by JoNilsson** [Kav-K/GPT3Discord#261]
**Describe the bug**
 
 This particular slash command `/index recurse-link` is not documented.

The assumption is that it would function similarly to the `/index add` command, possibly allowing a user of the command to specify the recursion depth?

Looking at the codebase, there are refs to this command here:

https://github.com/Kav-K/GPT3Discord/blob/7a18411e55279642b851aacc7c1675fd3147c4e4/cogs/index_service_cog.py#L123

https://github.com/Kav-K/GPT3Discord/blob/7a18411e55279642b851aacc7c1675fd3147c4e4/models/index_model.py#L483

https://github.com/Kav-K/GPT3Discord/blob/7a18411e55279642b851aacc7c1675fd3147c4e4/cogs/commands.py#L690

**To Reproduce**
use the `/index recurse-link` command, and provide a link to generate the error. 

**Expected behavior**
It is not apparent what the expected behavior is?  

**Screenshots**
<img width="597" alt="image" src="https://user-images.githubusercontent.com/54599325/231255362-fdedbfae-990b-4852-85bd-aff0c8a9c762.png">

**Comment by Kav-K** [comment]
Hey! This feature hasn't actually been finished yet :)

**Comment by JoNilsson** [comment]
> Hey! This feature hasn't actually been finished yet :)

Ah.  That makes more sense now.  
Thanks for clarifying.
