### ISSUE TITLE
Agent Stopped due to Iteration Limit or Time Limit in internet chat

### ISSUE THREAD

**Issue by Jiankun-Huang** [Kav-K/GPT3Discord#266]
I've encountered an issue with the GPT3Discord repository when using the 'internet chat' feature. The agent randomly stops working due to reaching an iteration limit or time limit. This issue occurs unexpectedly and disrupts the user experience.

Steps to reproduce:
1. Set up the the Discord BOT.
2. Use the 'internet chat' feature.
3. Observe the agent randomly stopping at times due to iteration limit or time limit.

Expected behavior:
The agent should not stop unexpectedly and should be able to fix itself. 

Environment:
- OS: Ubuntu 22.04
- Specs: 97GB RAM, RTX 4090
- Packages: Latest versions

I would appreciate it if this issue could be investigated and resolved. Thank you!

**Comment by Kav-K** [comment]
I tried to fix this, check out version 11.3.2, if you're still having this issue re-open this issue.

Also, make sure that the users using the internet connected chat don't have any special characters in their discord names or anythings like slashes, etc
