### ISSUE TITLE
Add a chat preamble feature

### ISSUE THREAD

**Issue by rolanddeboer** [Kav-K/GPT3Discord#30]
It would be cool to be able to add a preamble that gets inserted at the start of every prompt, even when the rest gets summarized. This can be used for example to define the character that the bot should play.

A possible way in which this could be set by the user is by issuing a command: !gp <preamble>

**Comment by Kav-K** [comment]
Roadmapped! Lets discuss a bit more though, you want each user to be able to set their own preamble, right?

**Comment by rolanddeboer** [comment]
Yes, that would be something that can be set for each conversation individually.

**Comment by rolanddeboer** [comment]
Almost like a sticky first message in a chat.

**Comment by Kav-K** [comment]
What if it's added as a parameter to the `!g converse` command? `!g converse <conversation prompt>`

**Comment by Kav-K** [comment]
Updated to using slash commands, the chat command is now /chat-gpt, I can just add another parameter to that command to have the conversation preamble :)

**Comment by rolanddeboer** [comment]
That sounds like the best way to do it. I will put in some time today in installing this and playing a bit with the code.

/chat-gpt though? Isn't that name confusing since it suggests that it uses the same model as ChatGPT? Maybe it is time for your bot to have a name. Maybe a simple, unassuming human name that fits with the theme of it talking in a natural, casual language.

**Comment by rolanddeboer** [comment]
Or else perhaps change the /chat-gpt command to /chat?
