### ISSUE TITLE
Include the prompt in /g output

### ISSUE THREAD

**Issue by Hikari-Haru** [Kav-K/GPT3Discord#38]
When /g is used it only shows the output as it is. I'd recommend including the input in the output but bold it so if the output is a natural continuation of the prompt it'll keep the context 

![Screenshot_20221231-213147~2.png](https://user-images.githubusercontent.com/15952522/210155151-f095b875-86ec-49d2-8001-90e715dd3419.png)

Here the prompt is "What would happen if "

**Comment by Kav-K** [comment]
The input is already visible if you click on the slash command execution though, did you know about that?

**Comment by Hikari-Haru** [comment]
Maybe an alternative command that doesn't include all the GPTie and other extra things. Just purely prompt in and generation out then combining them both to send

**Comment by Hikari-Haru** [comment]
> The input is already visible if you click on the slash command execution though, did you know about that?

Hadn't seen that, but it's kinda out of the way and bothersome if you want to do rapid fire prompt generation with a group of people where it'll quickly become messy clicking on the small "/g" on each message if you want to see the prompts

**Comment by Kav-K** [comment]
Yes I agree, I'll add the prompt field in! It'll have to be a bit deprioritized though, as I'd like to get pinecone working first :) 



> Maybe an alternative command that doesn't include all the GPTie and other extra things. Just purely prompt in and generation out then combining them both to send

What do you mean by "All the GPTie and other extra things"?

**Comment by Hikari-Haru** [comment]
> Yes I agree, I'll add the prompt field in! It'll have to be a bit deprioritized though, as I'd like to get pinecone working first :) 
> 
> 
> 
> > Maybe an alternative command that doesn't include all the GPTie and other extra things. Just purely prompt in and generation out then combining them both to send
> 
> What do you mean by "All the GPTie and other extra things"? Can you show me a screenshot of what you mean?

That's fair, this is what I mean.

![Screenshot_20221231-214148~2.png](https://user-images.githubusercontent.com/15952522/210155303-7ec33bb4-56cd-4cde-8e8a-115f7537d482.png)

**Comment by Kav-K** [comment]
Oh haha, so that happens because there is a "GPTie:" appended after the prompt as a fast way to simulate a more conversational response to your prompt, if you don't terminate your prompt or you leave it open ended, GPT3 will get creative and interpret it by itself

**Comment by Kav-K** [comment]
I will play around locally with removing the "GPTie:" text and see what's up

**Comment by Hikari-Haru** [comment]
> Oh haha, so that happens because there is a "GPTie:" appended after the prompt as a fast way to simulate a more conversational response to your prompt, if you don't terminate your prompt or you leave it open ended, GPT3 will get creative and interpret it by itself

Yeah that's what I figured, it'd just be nice to have nice raw message passing if left open and the prompt included so the prompt could flow into the output. Since a lot of us prompt engineer and having unexpected things added to it makes it behave differently. Since we're using slash commands it could be an option to run it "creatively" like it currently is though

**Comment by Kav-K** [comment]
Could you please make a separate small issue for the removal of GPTie:? I'll get on that immediately, I think you're definitely right and it makes it very restrictive for creative activity. Also, I've commented on pr 35 for a review

**Comment by Kav-K** [comment]
I've completed this! The prompt now shows 
![image](https://user-images.githubusercontent.com/21161101/210156044-8effcaf7-4d8a-4f07-b266-3f0198f4e1ad.png)
