### ISSUE TITLE
[BUG] Extra text appended to the prompt of /g

### ISSUE THREAD

**Issue by Hikari-Haru** [Kav-K/GPT3Discord#39]
**Describe the bug**
Bot might include GPTie or behave unexpectedly due to text appended to the prompt.

**To Reproduce**
Use /g and leave the prompt open

**Expected behavior**
Generate output using only the input.

**Screenshots**
![Screenshot_20221231-214148~2.png](https://user-images.githubusercontent.com/15952522/210155591-a2edb7d9-913b-4828-aff8-d45c1f8a8338.png)

**Comment by Kav-K** [comment]
On it!

**Comment by Kav-K** [comment]
Done!
