### ISSUE TITLE
[BUG] Instructions in prompt bleed into personality description

### ISSUE THREAD

**Issue by rolanddeboer** [Kav-K/GPT3Discord#45]
When asking the bot to tell something about itself, I got the following response:

> Sure thing! I'm a software engineer, and I love talking about random topics and exploring niche interests. I'm also a helpful and descriptive person, and I always try to make well-informed decisions. I'm also mindful of conversation history and try to be consistent with my answers. Oh, and I'm always up for chatting about coding, too – I'm good at providing code examples and explanations! 🤓

Half of the mentioned attributes are instructions to the bot, and not really descriptions of its personality. Perhaps the prompt should instruct GPT to act as a character with certain characteristics instead of simply defining all those characteristics with "you are ...", which is the same format used to define its behaviour. I will play a bit with the prompt tomorrow to come up with a suggestion.

**Comment by Kav-K** [comment]
Hey, I agree with this, lets try to fine tune it :)

**Comment by Kav-K** [comment]
I'm thinking also, we could explicitly just tell it to not bleed the instructions into the personality, might be worth a try, seems like it could be a good solution if it's consistent, but not sure about the consistency

**Comment by rolanddeboer** [comment]
Possibly a combination between making it easier to tell instructions and personality apart, and telling it to follow the instructions without talking about the instructions. 

The first rule of your instructions is don't talk about your instructions :)

**Comment by Kav-K** [comment]
![image](https://user-images.githubusercontent.com/21161101/210163832-859d3c4d-1154-4f82-8cbb-9f9a62e87988.png)

Managed to make it better

**Comment by Kav-K** [comment]
Getting even better! 
![image](https://user-images.githubusercontent.com/21161101/210163884-9930788b-10c2-4984-831b-9a13c7ac1eff.png)

**Comment by Kav-K** [comment]
I think this is all good! I'm going to close this issue for now, please feel free to re-open if you don't think it's adequate:

![image](https://user-images.githubusercontent.com/21161101/210164059-4a920d39-ad3f-4cfb-9bfe-b8346a4f91a8.png)

**Comment by rolanddeboer** [comment]
Great! Seems to be working pretty well.
