### ISSUE TITLE
Allow for a way to let all users use the bot

### ISSUE THREAD

**Issue by Kav-K** [Kav-K/GPT3Discord#50]
Currently, only users with the roles defined in `ALLOWED_ROLES` in `.env` will be able to use the bot, add a way to default it such that all users can use the bot (e.g, if no ALLOWED_ROLES, then everyone can use), open to any implementation/suggestions on this

**Comment by KarlKennerley** [comment]
Are there specific commands you don't want everyone to use? Could make separate lists eg, "Admin roles", "User roles" and check the user has the right role to use the command.

**Comment by Kav-K** [comment]
Yeah, the admin commands should be locked to admin roles even if everyone can use the gpt and dalle commands, this should probably be worked on after #48 is merged, as that’ll make it easier, I’ll merge 48 later today when I get home

**Comment by Hikari-Haru** [comment]
Can't the allow everyone just be checking if the env role list is empty then returning true in the role check functions?

**Comment by Kav-K** [comment]
Yeah that sounds perfect, the empty idea, we’d do that for dalle and gpt group commands and not do it for Admin group commands

**Comment by Hikari-Haru** [comment]
Yeah it's pretty simple

**Comment by Kav-K** [comment]
This is done! Check out the README for more info
