### ISSUE TITLE
User Provided API keys 

### ISSUE THREAD

**Issue by BEpresent** [Kav-K/GPT3Discord#62]
Hello, I was wondering if it would be possible to allow users to provide their own API keys in a secure manner, rather than using a single admin-provided key for all API calls. If this is not feasible, please let me know. One way I envision this being implemented is by prompting the user for their keys before the first use and temporarily saving them in an inaccessible cache.

Thank you for considering this suggestion. If this has been discussed previously, please excuse my duplication of the topic.

**Comment by Hikari-Haru** [comment]
I don't think it would be difficult to allow users to provide their own, but since the tokens are passed to openai as plaintext nothing is stopping the one on the machine it's run on from intercepting that as far as I know

**Comment by Kav-K** [comment]
Yes this is also my main concern with this, the server owner will be able to see any API keys the users provide

**Comment by BEpresent** [comment]
I see, this makes sense and this was one of main concerns - the best case would be that the server owners themselves  would not be able to see any stored key. There is no encryption possible?

**Comment by Kav-K** [comment]
Encryption is possible, but before we send the request we always need to decrypt the key to populate the correct request field with the auth token, so the owner will always be able to see it

**Comment by Kav-K** [comment]
Closing this, this is going to be continued in #72

**Comment by BEpresent** [comment]
Thanks, https://github.com/Kav-K/GPT3Discord/issues/72  is a great enhancement.
