### ISSUE TITLE
Redo button not working

### ISSUE THREAD

**Issue by Kav-K** [Kav-K/GPT3Discord#66]
Redo button always seems to throw an error, should be a quick fix, I’ll be on it soon!

**Comment by Hikari-Haru** [comment]
Already fixed this in my fork, it's due to the `encapsulated_send` in the `RedoButton` not having `response_message` keyworded so it sets the message to the `temp_override`

**Comment by Kav-K** [comment]
Oops totally didn't catch that earlier, thank you! Will review soon
