### ISSUE TITLE
Better, more accurate and more human-like translations using DeepL

### ISSUE THREAD

**Issue by CrypticHeaven-Lab** [Kav-K/GPT3Discord#67]
**Is your feature request related to a problem? Please describe.**
While I think the translations of GPT3 are correct in content, they often seem too edgy and clinical to me. Which somehow doesn't fit to a bot, which tries to get as close as possible to a human interlocutor.

**Describe the solution you'd like**
I would like to have the best possible and most accurate human-like translation.

**Describe alternatives you've considered**
DeepL is apparently currently the best translator. With really fascinating results.

**Additional context** (Sorry for that copycat down there... Dx)
- Unlike other services, the neural networks of DeepL can detect even the smallest nuances and reflect them in the translation. Not only does DeepL achieve record results in scientific benchmarks, but in blind tests translators also prefer the results of DeepL three times more often than those of the competition.

* When using DeepL Pro, your data is protected with the highest security measures. We guarantee DeepL Pro subscribers that all texts are deleted immediately after the translation has been completed, and that the connection to our servers is always encrypted. This means that your texts are not used for any purposes other than your translation, nor can they be accessed by third parties.

+ With DeepL Pro, you can translate an entire document with one click. All fonts, images, and formatting remain in place, leaving you free to edit the translated document any way you like.

- It can translate your Microsoft Word (.docx), PowerPoint (.pptx), PDF (.pdf), and text (.txt) files. Further formats coming soon!

* If you sign up for the DeepL API plan, you will be able to integrate DeepL’s JSON-based REST API into your own products and platforms. This allows you to incorporate the world’s best machine translation technology into a variety of new applications. For example, a company could have their international service enquiries instantly translated by DeepL Pro, greatly simplifying business procedures and improving customer satisfaction.

+ Freelance translators, translation agencies, language service providers, or corporate language departments can all benefit from using DeepL Pro, the world’s best machine translation technology, in their CAT Tool.

[DeepL - Translator](https://www.deepl.com/translator)
[DeepL - Press](https://www.deepl.com/press)
[DeepL - ProAPI](https://www.deepl.com/pro-api?cta=header-pro-api/)
[Why using DeepL instead of other translators?](https://www.deepl.com/whydeepl/)

**Comment by Kav-K** [comment]
Roadmapped!

**Comment by Kav-K** [comment]
Finished! Will iterate on things like the “formal” functionality and etc in the future
