### ISSUE TITLE
[BUG] Awaiting thread is already removed when using an opener

### ISSUE THREAD

**Issue by Hikari-Haru** [Kav-K/GPT3Discord#68]
Oopsied adding a line and didn't check. 
Remove `self.awaiting_thread_responses.remove(thread.id)` on line 1051

Also change `ctx.user.name` to `ctx.user.display_name` just above too

**Comment by Hikari-Haru** [comment]
I'm not sure why I have to remove the user there but the thread gets removed just fine

**Comment by Hikari-Haru** [comment]
Okay I actually found some time to look over it, `thread_message` in `/gpt converse` is the bot's first thread message which is passed to `encapsulated_send` as the ctx. In which the function will add the bot to the `awaiting_responses`  list then remove the bot from the `awaiting_responses` list. Outside of that the user is also blocked in the `if opener` `/gpt converse` statement

**Comment by Kav-K** [comment]
Fixed this, will be available in newest main, feel free to reopen if there's still any issues, I also checked and I don't think the bot gets added to the awaiting_responses list, the encapsulated_send function doesn't do any additions to that list, only removals if I'm seeing correctly, but I might be having a blind moment 😅

**Comment by Hikari-Haru** [comment]
> Fixed this, will be available in newest main, feel free to reopen if there's still any issues, I also checked and I don't think the bot gets added to the awaiting_responses list, the encapsulated_send function doesn't do any additions to that list, only removals if I'm seeing correctly, but I might be having a blind moment 😅 

Oh yeah you're right there, was thinking of the whole on_message -> encapsulated_send chain haha
