### ISSUE TITLE
Fixing warning errors in logs 

### ISSUE THREAD

**Issue by yigitkonur** [Kav-K/GPT3Discord#8]
The bot works great! Thank you for creating such an amazing software.

<img width="1282" alt="CleanShot 2022-12-19 at 10 30 58@2x" src="https://user-images.githubusercontent.com/9989650/208405561-e15bc570-a75f-4c5e-9f7b-49f9bbdd9a36.png">

When I monitor logs, I've seen that there are some cases that needs error handling. I just want to share them if you mind to fix them.

**Comment by Kav-K** [comment]
Yup! Thanks for sharing! Looks like I've forgotten to do some user checks, I'll have it fixed up and have a better logging/debug suite implemented within a few days.

**Comment by Kav-K** [comment]
This is done!
