### ISSUE TITLE
Purge Non-ASCII characters from Discord usernames so it doesn't error out when sending data to Pinecone

### ISSUE THREAD

**Issue by noalear** [Kav-K/GPT3Discord#84]
Our entire Discord server has special non-ascii characters as the first character to denote rank. It would be nice if unfriendly characters were stripped out before the data is sent to Pinecone as it causes conversations to end immediately.

Error shown below: 

> pinecone.core.client.exceptions.ApiException: (400)
> Reason: Bad Request
> HTTP response headers: HTTPHeaderDict({'content-type': 'application/json', 'date': 'Wed, 11 Jan 2023 01:33:10 GMT', 'x-envoy-upstream-service-time': '0', 'content-length': '129', 'server': 'envoy'})
> HTTP response body: {"code":3,"message":"ID must be ASCII, but got \n'⧋ Noa [SCALPEL-3]': Hi newthena \u003c|endofstatement|\u003e\n","details":[]}

Screenshot on the user side:
![image](https://user-images.githubusercontent.com/121597528/211702554-96e34ef3-b43f-4319-91ff-b9a02aa8663a.png)

Keep up the great work! Love the new features.

**Comment by Kav-K** [comment]
Hi! This is indeed an important bug, I've marked this as high priority and it should be available in the next few releases within 24h-ish

**Comment by Kav-K** [comment]
Actually, this was quick, I just pushed up a change to main, can you confirm it's all good @noalear?

**Comment by Kav-K** [comment]
Reopen if not all good! It's in release v5.0.1

**Comment by noalear** [comment]
That worked like a charm! Nice work @Kav-K!
