### ISSUE TITLE
[BUG] Message edits in conversation don't work with pinecone enabled

### ISSUE THREAD

**Issue by Hikari-Haru** [Kav-K/GPT3Discord#88]
**Describe the bug**
Messsage edits don't redo the prompt when pinecone is enabled

**To Reproduce**
1. enable pinecone
2. start conversation
3. send message
4. edit the message

**Expected behavior**
The bot redoes the prompt as usual

**Screenshots**
```python
Traceback (most recent call last):
  File "/home/bots/.local/lib/python3.9/site-packages/discord/client.py", line 377, in _run_event
    await coro(*args, **kwargs)
  File "/home/bots/discord_bots/GPT3Discord/cogs/gpt_3_commands_and_converser.py", line 605, in on_message_edit
    edited_content = "".join(
TypeError: sequence item 0: expected str instance, EmbeddedConversationItem found
```

**Comment by Kav-K** [comment]
I'm not able to replicate this on my instance, did you fix this in your previous PR?

**Comment by Kav-K** [comment]
Fixed in latest
