### ISSUE TITLE
When i run on my EC2 AWS Instance

### ISSUE THREAD

**Issue by akshaynstack** [Kav-K/GPT3Discord#94]
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

**Comment by Kav-K** [comment]
Please make sure of the following:
- ALLOWED_GUILDS in your `.env` file should not have the IDs of any servers that your bot is NOT a part of
- your bot needs all of the privileged intents in the discord developer portal
- Your bot needs the "bot" scope when generating a URL with URL generator on the discord developer portal

**Comment by akshaynstack** [comment]
Thank you so much, the issue is resolved, this is the best support i ever got. Thanks 💯
